-- ─────────────────────────────────────────────────────────────────
-- Translucent Pro: Supabase Cloud Database Schema
-- Run this in your Supabase SQL Editor:
-- https://supabase.com/dashboard/project/rcpwboqmcqzrcpyomfmu/sql/new
-- ─────────────────────────────────────────────────────────────────

-- 1. Users Table
CREATE TABLE IF NOT EXISTS public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    google_id TEXT UNIQUE,
    email TEXT UNIQUE NOT NULL,
    name TEXT,
    avatar_url TEXT,
    status TEXT DEFAULT 'pending',
    plan TEXT DEFAULT 'pro',
    expires_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    last_active_at TIMESTAMPTZ DEFAULT NOW(),
    notes TEXT,
    active_device_id TEXT,
    active_device_name TEXT,
    active_session_token TEXT
);

-- 2. Settings Table
CREATE TABLE IF NOT EXISTS public.settings (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL
);

-- 3. Default Admin / Owner (Rohit Kumar - Lifetime Pro)
INSERT INTO public.users (email, name, status, plan, created_at, last_active_at)
VALUES ('un.rohitkumar@gmail.com', 'Rohit Kumar', 'active', 'lifetime', NOW(), NOW())
ON CONFLICT (email) DO UPDATE SET status = 'active', plan = 'lifetime';

-- 4. Enable Row Level Security (RLS) & Grant Access
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read and write for users" ON public.users FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read and write for settings" ON public.settings FOR ALL USING (true) WITH CHECK (true);
